# For the Zed Camera, a WIP
# This is heavily based off the PtGrey stereo error model: https://www.ptgrey.com/KB/10589
sensor_processor/type: Stereo2

#Baseline units: meters
sensor_processor/base_line: 0.120

#This is fx, units: pixels
sensor_processor/focal_length: 341.925201

#As defined by PtGrey, experimental value
#TEMPORARY OVERRIDDED: matching = base error (intercept, c), pointing = constant measure distance factor(m)
#using variance = m*x+c
sensor_processor/matching_error: 0.0010
sensor_processor/pointing_error: 0.0030

#Units: Meters, trims all points outside these depths away.
sensor_processor/cutoff_min_depth: 0.1
sensor_processor/cutoff_max_depth: 2.5
sensor_processor/ignore_points_above: 2.0
sensor_processor/ignore_points_below: -1.0
