# For the Zed Camera, a WIP
sensor_processor/type: Stereo2

#This seems to be a constant error per distance. eg 0.001m error per meter of measurement LATTERALLY. Testing made up values atm
sensor_processor/lateral_factor: 0.05

#experimental scaling value
sensor_processor/normal_factor: 0.05

# This should be focal length * baseline. Units? For ZED VGA: 341.93*0.12
sensor_processor/depth_to_disparity_factor: 41.0316

# Depth cutting filter
sensor_processor/cutoff_min_depth: 1.5
sensor_processor/cutoff_max_depth: 5.0

# Down sampling filter
sensor_processor/down_sample_radius: 0.025

#Outlier Removal filter
sensor_processor/neighbour_radius: 0.25
sensor_processor/min_neighbours: 5.0
