# Traversability map filter parameters
# crit_slope: critical_value: 1.56
# 2/3 of 90 degrees: critical_value: 1.0471975512
traversability_map_filters:
  - name: surfaceNormalsFilter
    type: traversabilityFilters/SurfaceNormalsFilter
    params:
      estimation_radius: 0.04
      surface_normal_positive_axis: "z"
  - name: slopeFilter
    type: traversabilityFilters/SlopeFilter
    params:
      map_type: traversability_slope
      critical_value: 0.7
  - name: stepFilter
    type: traversabilityFilters/StepFilter
    params:
      map_type: traversability_step
      critical_value: 0.10
      first_window_radius: 0.075
      second_window_radius: 0.075
      critical_cell_number: 10
#  - name: roughnessFilter
#    type: traversabilityFilters/RoughnessFilter
#    params:
#      map_type: traversability_roughness
#      critical_value: 0.075
#      estimation_radius: 0.05
# - name: minFilter
#   type: gridMapFilters/MinFilter
#   params:
#    layers: [traversability_slope, traversability_step, traversability_roughness]
#    layer_out: traversability
# - name: lowerThresholdFilter
#   type: gridMapFilters/ThresholdFilter
#   params:
#    lower_threshold: 0.2
#    set_to: 0.0
#    layers: [traversability]
# - name: upperThresholdFilter
#   type: gridMapFilters/ThresholdFilter
#   params:
#    upper_threshold: 0.9
#    set_to: 1.0
#    layers: [traversability]
  - name: weightedSumFilter
    type: gridMapFilters/WeightedSumFilter
    params:
      layers: [traversability_slope, traversability_step] #layers: [traversability_slope, traversability_step, traversability_roughness]
      weights: [0.1, 1]
      layer_out: traversability
      normalize: 1
  - name: deletionFilter
    type: gridMapFilters/DeletionFilter
    params:
      layers: [surface_normal_x, surface_normal_y, surface_normal_z]
