grid_map_visualizations:

  - name: elevation_cloud
    type: point_cloud
    params:
     layer: elevation

  - name: sigma_cloud
    type: point_cloud
    params:
     layer: two_sigma_bound

  - name: map_region
    type: map_region
    params:
     color: 16777215
     line_width: 0.003

  - name: surface_normals
    type: vectors
    params:
     layer_prefix: surface_normal_
     position_layer: elevation
     scale: 0.03
     line_width: 0.001
     color: 16777215
