length_in_x: 5.0
length_in_y: 5.0
position_x: 0.0
position_y: 0.0
resolution: 0.025
min_variance: 0.002
max_variance: 0.05
mahalanobis_distance_threshold: 2.5
multi_height_noise: 0.002
surface_normal_estimation_radius: 0.075
surface_normal_positive_axis: z
